package uk.co.baconi.games.tag.engine

enum class Room {
    FrontPath,
    Drive,
    Garage,
    Porch,
    Hallway,
    Dining,
    Kitchen,
    Pantry,
    BackPassage,
    Utility,
    Yard,
    Garden,
    ToolShed,
    CoalShed,
    SummerHouse,
    TreeHouse,
    GreenHouse,
    VeggiePatch,
    Field,
    UnderTheStairs,
    Lounge,
    Conservatory,
    ChimneyStack,
    StairCase,
    Landing,
    FirstBedroom,
    SecondBedroom,
    Toilet,
    Bathroom,
    Attic,
    Roof,
    ThirdBedroom,
    FourthBedroom,
}